default:
    image: hub.ilearned.eu/i-learned/ci-cd/blog-builder

stages:
    - prod-deploy

prod-deploy-job:
    stage: prod-deploy
    script:
        - apt update
        - apt install wget tar -y
        - wget https://github.com/tdewolff/minify/releases/download/v2.10.0/minify_linux_amd64.tar.gz
        - tar -xf minify_linux_amd64.tar.gz -C /tmp
        - mv /tmp/minify /bin
        - minify --html-keep-comments -r -o ./ ./
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - echo "$SSH_EBANVM01_PRIVATE_KEY" > ~/.ssh/id_ed25519
        - chmod 600 ~/.ssh/id_ed25519
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" ./ deploy@vm01.eban.eu.org:/var/www/html
    only:
        - main
